FROM python:3.12-slim

WORKDIR /app

COPY frontend/requirements.txt .

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
RUN uv pip install -r requirements.txt --system

RUN huggingface-cli download allenai/specter2_base
RUN huggingface-cli download allenai/specter2

COPY frontend/ .

EXPOSE 8080

CMD streamlit run app.py --server.port=${PORT:-8080} --server.address=0.0.0.0
